// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqiiSU165UIMN_IwgtF6A5CfZUJ31sHnU',
    appId: '1:161267781075:web:11556eba6e67b3e2d27326',
    messagingSenderId: '161267781075',
    projectId: 'biiz-299a7',
    authDomain: 'biiz-299a7.firebaseapp.com',
    storageBucket: 'biiz-299a7.firebasestorage.app',
    measurementId: 'G-X7KFBNXJTT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAeGZEJ10nq8lmdzrGkLheIJVPwHX0RKU',
    appId: '1:161267781075:android:1c39d93e333044bed27326',
    messagingSenderId: '161267781075',
    projectId: 'biiz-299a7',
    storageBucket: 'biiz-299a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTAmA4AeJPfyhznUM2vFpGWDKZxgimj2g',
    appId: '1:161267781075:ios:323fbd2bfa89ca2cd27326',
    messagingSenderId: '161267781075',
    projectId: 'biiz-299a7',
    storageBucket: 'biiz-299a7.firebasestorage.app',
    iosBundleId: 'com.cudiyildiz.biiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTAmA4AeJPfyhznUM2vFpGWDKZxgimj2g',
    appId: '1:161267781075:ios:323fbd2bfa89ca2cd27326',
    messagingSenderId: '161267781075',
    projectId: 'biiz-299a7',
    storageBucket: 'biiz-299a7.firebasestorage.app',
    iosBundleId: 'com.cudiyildiz.biiz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqiiSU165UIMN_IwgtF6A5CfZUJ31sHnU',
    appId: '1:161267781075:web:f54b838e711e26dcd27326',
    messagingSenderId: '161267781075',
    projectId: 'biiz-299a7',
    authDomain: 'biiz-299a7.firebaseapp.com',
    storageBucket: 'biiz-299a7.firebasestorage.app',
    measurementId: 'G-HNS8ZNWXW3',
  );
}
